apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: control
      port: 21
      targetPort: 21
      protocol: TCP
    - name: transfer1
      port: 21001
      targetPort: 21001
      protocol: TCP
    - name: transfer2
      port: 21002
      targetPort: 21002
      protocol: TCP
    - name: transfer3
      port: 21003
      targetPort: 21003
      protocol: TCP
    - name: transfer4
      port: 21004
      targetPort: 21004
      protocol: TCP
    - name: transfer5
      port: 21005
      targetPort: 21005
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps-img
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 21001
            - containerPort: 21002
            - containerPort: 21003
            - containerPort: 21004
            - containerPort: 21005