apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
  labels:
    app: telegraf
spec:
  selector:
    app: telegraf
  type: ClusterIP
  ports:
    - port: 886
      targetPort: 886
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf-img
          imagePullPolicy: Never
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
          ports:
            - containerPort: 886
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock